"""ORM models.

Every model must be imported here. Alembic reads Base.metadata through this
package, and a model that is missing would be autogenerated as a table to drop.
"""

from app.database.models.approvals import Approval, AuditEvent
from app.database.models.base import Base
from app.database.models.delegation import DelegationPlan, DelegationPlanItem
from app.database.models.messaging import MessagingIdentity
from app.database.models.organizations import Membership, Organization, User
from app.database.models.outbox import OutboundMessage
from app.database.models.work import TaskEvent, WorkItem

__all__ = [
    "Approval",
    "AuditEvent",
    "Base",
    "DelegationPlan",
    "DelegationPlanItem",
    "Membership",
    "MessagingIdentity",
    "Organization",
    "OutboundMessage",
    "TaskEvent",
    "User",
    "WorkItem",
]
