"""Column mixins shared by every table."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by PostgreSQL.

    Generating server-side keeps identifiers consistent no matter which client
    inserts the row. gen_random_uuid() is core since PostgreSQL 13, so no
    extension is required.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at, stored as UTC.

    TIMESTAMPTZ normalises to UTC on write. updated_at is maintained by the ORM,
    which is sufficient while every write goes through a session; a trigger would
    be needed if raw SQL ever started mutating these tables.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
